.

diff --git a/.github/workflows/git_add_tag.yml b/.github/workflows/git_add_tag.yml
--- a/.github/workflows/git_add_tag.yml
+++ b/.github/workflows/git_add_tag.yml
@@ -26,9 +26,7 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           TAG_VERSION: ${{ github.event.inputs.tag_version }}
-
-      - name: if failed
-         if: failure()
-         run: |
-           echo 'failed'
-           && exit 1
+        if: failure()
+        run: |
+          echo 'failed'
+          && exit 1
