syntax error

diff --git a/.github/workflows/git_add_tag.yml b/.github/workflows/git_add_tag.yml
--- a/.github/workflows/git_add_tag.yml
+++ b/.github/workflows/git_add_tag.yml
@@ -27,8 +27,8 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           TAG_VERSION: ${{ github.event.inputs.tag_version }}
 
-     - name: if failed
-        if: failure()
-        run: |
-          echo 'failed'
-          && exit 1
+      - name: if failed
+         if: failure()
+         run: |
+           echo 'failed'
+           && exit 1
