.

diff --git a/.github/workflows/git_add_tag.yml b/.github/workflows/git_add_tag.yml
--- a/.github/workflows/git_add_tag.yml
+++ b/.github/workflows/git_add_tag.yml
@@ -22,24 +22,24 @@ jobs:
       - uses: actions/checkout@v2
 
       # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
-        run: |
-          git fetch --tags
-
-          head_commit=$(git show HEAD --format=format:"%H" | head -n 1)
-          latest_tag=$(git tag | tail -n 1)
-          latest_tag_commit=$(git show ${latest_tag} --format=format:"%H" | head -n 1)
-
-          # echo $latest_tag
-          # echo $head_commit
-          # echo $latest_tag_commit
-
-          if [ $head_commit = $latest_tag_commit ]; then
-            exit 0
-          else
-            echo 'tag missing on HEAD commit'
-            exit 1
-          fi
+      # - name: Run a multi-line script
+      #   run: |
+      #     git fetch --tags
+      #
+      #     head_commit=$(git show HEAD --format=format:"%H" | head -n 1)
+      #     latest_tag=$(git tag | tail -n 1)
+      #     latest_tag_commit=$(git show ${latest_tag} --format=format:"%H" | head -n 1)
+      #
+      #     # echo $latest_tag
+      #     # echo $head_commit
+      #     # echo $latest_tag_commit
+      #
+      #     if [ $head_commit = $latest_tag_commit ]; then
+      #       exit 0
+      #     else
+      #       echo 'tag missing on HEAD commit'
+      #       exit 1
+      #     fi
 
       - name: Github Tag Bump
         uses: naofumi-fujii/github-tag-action@master
